### ISSUE TITLE
Kodu Anlamak Hk.

### ISSUE THREAD

**Issue by Ahmopasa** [OzanCansel/tableprinter#2]
Merhaba. 
_tableprinter.hpp_ içerisinde yazmış olduğunuz aşağıdaki kod parçacığını anlamakta zorluk çektim. Acaba yazılanları anlamak konusunda beni yönlendirir misiniz? Örneğin, hangi konulara hakim olmalıyım vs.

`template<typename... Ts>`
`struct overloaded : Ts...`
`{`
`    using Ts::operator ()...;`
`};`

C++ öğrenmeye yeni başladım. _Variadic Template Arguments_ konusuna pek hakim olmadığım için tam olarak anlayamadım ne yapılmak istenildiğini. İnternetten baktığım kadarıyla _Variadic Template Data Structures_ konusu ile alakalı. 

Yardımcı olursanız çok sevinirim.

**Comment by OzanCansel** [comment]
Sorunun cevabını email adresine cevap olarak gönderiyorum.

Burada ingilizce dışında bir dil kullanmamız doğru olmadığı için bu issue'yı kapatıyorum Ahmet :)
